@startuml test
left to right direction
actor marcelo
actor directivo
rectangle sistema {
    marcelo -- (realizar inventario)
    (realizar inventario) ..> (mostrar items) : include
    (realizar inventario) ..> (cargar items) : include
    (ver inventario) ..> (mostrar items) : include
    directivo -- (ver inventario)
    directivo -- (ver alumnos)
}
@enduml